# Setup geral do docker
services:
 db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=circo
    volumes:
      - ./data:/var/lib/postgresql/data